In [2]:
# imports
import pandas as pd
import matplotlib.pyplot as plt

# import dataset for GDP from 
gdpData = "datasets/GDP.csv"


rawGDP_df = pd.read_csv(gdpData)

rawGDP_df.head()

  LOCATION INDICATOR SUBJECT  MEASURE FREQUENCY  TIME         Value Flag Codes
0      AUS       GDP     TOT  USD_CAP         A  1976   7376.230734        NaN
1      AUS       GDP     TOT  USD_CAP         A  1977   7706.213573        NaN
2      AUS       GDP     TOT  USD_CAP         A  1978   8529.813526        NaN
3      AUS       GDP     TOT  USD_CAP         A  1979   9429.932785        NaN
4      AUS       GDP     TOT  USD_CAP         A  1980  10448.465179        NaN